<main id="main-content">
    <section class="page-hero section legal-hero">
        <div class="shell page-hero-grid"><div data-reveal><span class="eyebrow"><span lang="fr">Informations légales</span><span lang="en">Legal information</span></span><h1><span lang="fr">Mentions légales.</span><span lang="en">Legal notice.</span></h1></div><div class="page-intro" data-reveal><p><span lang="fr">Dernière mise à jour : 18 juillet 2026.</span><span lang="en">Last updated: July 18, 2026.</span></p></div></div>
    </section>

    <section class="section section-contrast">
        <div class="shell legal-grid">
            <article class="legal-card" data-reveal><span>01</span><h2><span lang="fr">Éditeur</span><span lang="en">Publisher</span></h2><p>Hugo Bisserier<br>2 rue de la Fougasse<br>13100 Aix-en-Provence · France</p><p><a href="mailto:hugo.bisserier.pro@gmail.com">hugo.bisserier.pro@gmail.com</a></p></article>
            <article class="legal-card" data-reveal><span>02</span><h2><span lang="fr">Hébergement</span><span lang="en">Hosting</span></h2><p>Hostinger International Ltd.<br>61 Lordou Vironos Street<br>6023 Larnaca · Cyprus</p><p><a href="https://www.hostinger.com/" target="_blank" rel="noopener noreferrer">hostinger.com ↗</a></p></article>
            <article class="legal-card" data-reveal><span>03</span><h2><span lang="fr">Propriété intellectuelle</span><span lang="en">Intellectual property</span></h2><p lang="fr">Les textes, la structure du site, les visuels de projet et les éléments graphiques sont protégés. Les marques et noms de technologies cités restent la propriété de leurs titulaires respectifs.</p><p lang="en">The text, website structure, project visuals and graphic elements are protected. Mentioned technology names and trademarks remain the property of their respective owners.</p></article>
            <article class="legal-card" data-reveal><span>04</span><h2><span lang="fr">Responsabilité</span><span lang="en">Liability</span></h2><p lang="fr">Les informations sont présentées à titre professionnel et peuvent évoluer. Les liens externes sont fournis à titre pratique ; leur contenu relève de leurs éditeurs.</p><p lang="en">Information is provided for professional presentation and may evolve. External links are offered for convenience; their content remains the responsibility of their publishers.</p></article>
            <article class="legal-card" data-reveal><span>05</span><h2><span lang="fr">Sécurité & signalement</span><span lang="en">Security & reporting</span></h2><p lang="fr">Pour signaler de manière responsable un problème de sécurité concernant ce site, utilisez l’adresse e-mail ci-dessus avec un descriptif reproductible. N’accédez pas à des données qui ne vous appartiennent pas.</p><p lang="en">To responsibly report a security issue affecting this site, use the email address above and include reproducible details. Do not access data that does not belong to you.</p></article>
            <article class="legal-card" data-reveal><span>06</span><h2><span lang="fr">Droit applicable</span><span lang="en">Applicable law</span></h2><p lang="fr">Le présent site est soumis au droit français. Toute difficulté doit d’abord faire l’objet d’une tentative de résolution amiable.</p><p lang="en">This website is governed by French law. Any dispute should first be addressed through an amicable resolution attempt.</p></article>
        </div>
    </section>
</main>
