<main id="main-content">
    <section class="page-hero section legal-hero">
        <div class="shell page-hero-grid"><div data-reveal><span class="eyebrow"><span lang="fr">Vie privée</span><span lang="en">Privacy</span></span><h1><span lang="fr">Une politique simple pour un site simple.</span><span lang="en">A simple policy for a simple website.</span></h1></div><div class="page-intro" data-reveal><p><span lang="fr">Dernière mise à jour : 18 juillet 2026.</span><span lang="en">Last updated: July 18, 2026.</span></p></div></div>
    </section>

    <section class="section section-contrast">
        <div class="shell privacy-layout">
            <aside class="privacy-summary" data-reveal><span class="eyebrow"><span lang="fr">En bref</span><span lang="en">In short</span></span><h2><span lang="fr">Pas de compte. Pas de formulaire. Pas de publicité.</span><span lang="en">No account. No form. No advertising.</span></h2><p lang="fr">Le portfolio ne demande aucune donnée personnelle et n’utilise aucun outil d’analyse d’audience tiers.</p><p lang="en">This portfolio requests no personal data and uses no third-party audience analytics.</p></aside>
            <div class="privacy-content">
                <article data-reveal><span>01</span><div><h2><span lang="fr">Données collectées</span><span lang="en">Data collected</span></h2><p lang="fr">Aucune donnée n’est collectée directement par le site. Il n’existe ni formulaire, ni inscription, ni espace utilisateur, ni base de données applicative.</p><p lang="en">No data is collected directly by this website. There is no form, registration, user area or application database.</p></div></article>
                <article data-reveal><span>02</span><div><h2><span lang="fr">Préférences locales</span><span lang="en">Local preferences</span></h2><p lang="fr">La langue et le thème sont enregistrés dans le stockage local du navigateur. Ces préférences restent sur votre appareil et ne sont pas envoyées au serveur.</p><p lang="en">Language and theme are stored in your browser’s local storage. These preferences remain on your device and are not sent to the server.</p></div></article>
                <article data-reveal><span>03</span><div><h2><span lang="fr">Journaux techniques</span><span lang="en">Technical logs</span></h2><p lang="fr">Comme tout hébergeur, Hostinger peut conserver des journaux techniques nécessaires à la sécurité et au fonctionnement du service, notamment l’adresse IP, la date et la ressource demandée. Leur traitement relève de la politique de Hostinger.</p><p lang="en">Like any hosting provider, Hostinger may retain technical logs required for security and service operation, including IP address, date and requested resource. Their processing is governed by Hostinger’s policy.</p></div></article>
                <article data-reveal><span>04</span><div><h2><span lang="fr">Liens externes</span><span lang="en">External links</span></h2><p lang="fr">GitHub, LinkedIn, DEV Community, Discord et les sites de documentation appliquent leurs propres politiques. Leur ouverture résulte d’une action volontaire de votre part.</p><p lang="en">GitHub, LinkedIn, DEV Community, Discord and documentation websites apply their own policies. Opening them results from your voluntary action.</p></div></article>
                <article data-reveal><span>05</span><div><h2><span lang="fr">Contact</span><span lang="en">Contact</span></h2><p lang="fr">Si vous contactez Hugo Bisserier par e-mail ou via une plateforme externe, les informations transmises servent uniquement à répondre à votre demande. Vous pouvez demander leur suppression à tout moment.</p><p lang="en">If you contact Hugo Bisserier by email or through an external platform, submitted information is used only to answer your request. You may request its deletion at any time.</p></div></article>
                <article data-reveal><span>06</span><div><h2><span lang="fr">Vos droits</span><span lang="en">Your rights</span></h2><p lang="fr">Pour toute question relative à l’accès, la rectification ou la suppression d’un échange, écrivez à <a href="mailto:hugo.bisserier.pro@gmail.com">hugo.bisserier.pro@gmail.com</a>.</p><p lang="en">For any question about access, correction or deletion of an exchange, write to <a href="mailto:hugo.bisserier.pro@gmail.com">hugo.bisserier.pro@gmail.com</a>.</p></div></article>
            </div>
        </div>
    </section>
</main>
